version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend

